### ISSUE TITLE
Activity View: Referenced Commits

### ISSUE THREAD

**Issue by andrewshawcare** [rauhryan/huboard#181] opened 2013-06-13 16:33 UTC
The activity view should include referenced commits. I see the referenced commit in the issue view on GitHub, when I view the activity on Huboard there is no referenced commit.

**Comment by ehausen** [comment] 2015-07-02 15:55
I think this is a duplicate of #454 which seem to be given a milestone but it is blocked

Maybe you guys can vote there and thsi can be closed?

**Comment by ehausen** [comment] 2015-07-03 12:16
It seems that all the commit message references are incorrectly displayed "..few seconds ago.."

<img width="581" alt="screen shot 2015-07-03 at 14 13 29" src="https://cloud.githubusercontent.com/assets/6204129/8498990/dea26948-218d-11e5-8ae6-0c7cdc811c87.png">
<img width="460" alt="screen shot 2015-07-03 at 14 13 20" src="https://cloud.githubusercontent.com/assets/6204129/8498989/dea25e4e-218d-11e5-95e9-411797b2ebd5.png">
<img width="558" alt="screen shot 2015-07-03 at 14 12 44" src="https://cloud.githubusercontent.com/assets/6204129/8498991/dea37a4a-218d-11e5-93ae-a5bea57b25f0.png">
<img width="524" alt="screen shot 2015-07-03 at 14 12 14" src="https://cloud.githubusercontent.com/assets/6204129/8498992/dea7000c-218d-11e5-993e-113f34c094ad.png">

**Comment by rauhryan** [comment] 2015-07-03 13:23
Thanks for pointing this out, we'll take a look

Should be an easy fix

**Comment by discorick** [comment] 2015-10-21 13:10
Yep that feature has been implemented, and incorrect timestamp reporting has been fixed

**Closed by discorick** 2015-10-21 13:10 UTC
Labels: 4 - Deployed
