### ISSUE TITLE
Filter sidebar doesn't fully collapse in Firefox

### ISSUE THREAD

**Issue by seanlinsley** [rauhryan/huboard#472] opened 2015-01-06 21:15 UTC
When collapsing the filter sidebar, it only partially collapses when using Firefox.

Regular:

<img width="50%" src="https://cloud.githubusercontent.com/assets/688886/5636273/9ac8ac24-95be-11e4-9d1e-8989f56c09b3.png"/>

Collapsed:

<img width="50%" src="https://cloud.githubusercontent.com/assets/688886/5636272/9ac58d28-95be-11e4-9631-7e916ea4fb0f.png"/>

It seems like it's a flexbox bug. Disabling the `flex: 0 1 0%` attribute causes it to hide completely.

![screen shot 2015-01-06 at 3 57 22 pm](https://cloud.githubusercontent.com/assets/688886/5636330/23afa268-95bf-11e4-98d1-2f1e59fc681a.png)

**Comment by dealingwith** [comment] 2015-02-02 16:45
+1 to fix since I recently switch back to FF :)

**Comment by discorick** [comment] 2015-02-02 16:53
@dealingwith @seanlinsley, I am having trouble reproducing - would I be able to get the FF versions you are using ?

**Comment by dealingwith** [comment] 2015-02-02 16:59
35.0.1

**Comment by seanlinsley** [comment] 2015-02-02 17:33
Maybe it's specific to operating system? Both @dealingwith and myself are on OSX.

**Comment by dealingwith** [comment] 2015-02-02 17:43
We're also both still on Mavericks

**Comment by discorick** [comment] 2015-02-02 17:48
I was an upgrade behind on FF, once upgraded I get the same behavior. As @seanlinsley pointed out, it is indeed a flex issue - I guess new versions calculate the flex-basis property differently :thumbsdown:  . We should have a fix for this up in the next couple days!

**Comment by rauhryan** [comment] 2015-02-23 18:22
Deploying a fix now

**Closed by rauhryan** 2015-02-23 18:22 UTC
Labels: 4 - Deployed, Defect

**Comment by seanlinsley** [comment] 2015-03-16 15:41
This is happening again:

![screen shot 2015-03-16 at 10 40 24 am](https://cloud.githubusercontent.com/assets/688886/6669802/eeffa168-cbc8-11e4-8a31-35e66bdde44c.png)

**Comment by rauhryan** [comment] 2015-03-16 16:11
Sorry about that, we had a long running branch while porting all the server side code over to ruby on rails. 

Just deployed the fix

**Comment by seanlinsley** [comment] 2015-03-16 22:11
:+1: thanks :-)
